// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NurseryAngularApplication.Model;

namespace NurseryAngularApplication.Migrations
{
    [DbContext(typeof(NursaryContext))]
    [Migration("20200702131338_Added-table-Farmer")]
    partial class AddedtableFarmer
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NurseryAngularApplication.Model.Employee.EmployeeDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateofBirth")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<int>("EducationType")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenderType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NurseryId")
                        .HasColumnType("int");

                    b.Property<int?>("StateId")
                        .HasColumnType("int");

                    b.Property<int?>("TehsilId")
                        .HasColumnType("int");

                    b.Property<string>("VillageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("NurseryId");

                    b.HasIndex("StateId");

                    b.HasIndex("TehsilId");

                    b.ToTable("EmployeeDetails");
                });

            modelBuilder.Entity("NurseryAngularApplication.Model.Farmers.Farmer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DateofBirth")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<int>("EducationType")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("GenderType")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NurseryId")
                        .HasColumnType("int");

                    b.Property<int?>("StateId")
                        .HasColumnType("int");

                    b.Property<int?>("TehsilId")
                        .HasColumnType("int");

                    b.Property<string>("VillageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("NurseryId");

                    b.HasIndex("StateId");

                    b.HasIndex("TehsilId");

                    b.ToTable("Farmers");
                });

            modelBuilder.Entity("NurseryAngularApplication.Model.Nurserys.Nursery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ContactNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("EmailId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MiddleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NurseryName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("StateId")
                        .HasColumnType("int");

                    b.Property<int?>("TehsilId")
                        .HasColumnType("int");

                    b.Property<string>("VilageName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.HasIndex("StateId");

                    b.HasIndex("TehsilId");

                    b.ToTable("Nurserys");
                });

            modelBuilder.Entity("NurseryAngularApplication.Model.States.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DistrictName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int?>("StateId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("NurseryAngularApplication.Model.States.State", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("StateName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("States");
                });

            modelBuilder.Entity("NurseryAngularApplication.Model.States.Tehsil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime?>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DistrictId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("TehsilName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("DistrictId");

                    b.ToTable("Tehsils");
                });

            modelBuilder.Entity("NurseryAngularApplication.Model.Employee.EmployeeDetail", b =>
                {
                    b.HasOne("NurseryAngularApplication.Model.States.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId");

                    b.HasOne("NurseryAngularApplication.Model.Nurserys.Nursery", "Nursery")
                        .WithMany()
                        .HasForeignKey("NurseryId");

                    b.HasOne("NurseryAngularApplication.Model.States.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId");

                    b.HasOne("NurseryAngularApplication.Model.States.Tehsil", "Tehsil")
                        .WithMany()
                        .HasForeignKey("TehsilId");
                });

            modelBuilder.Entity("NurseryAngularApplication.Model.Farmers.Farmer", b =>
                {
                    b.HasOne("NurseryAngularApplication.Model.States.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId");

                    b.HasOne("NurseryAngularApplication.Model.Nurserys.Nursery", "Nursery")
                        .WithMany()
                        .HasForeignKey("NurseryId");

                    b.HasOne("NurseryAngularApplication.Model.States.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId");

                    b.HasOne("NurseryAngularApplication.Model.States.Tehsil", "Tehsil")
                        .WithMany()
                        .HasForeignKey("TehsilId");
                });

            modelBuilder.Entity("NurseryAngularApplication.Model.Nurserys.Nursery", b =>
                {
                    b.HasOne("NurseryAngularApplication.Model.States.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId");

                    b.HasOne("NurseryAngularApplication.Model.States.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId");

                    b.HasOne("NurseryAngularApplication.Model.States.Tehsil", "Tehsil")
                        .WithMany()
                        .HasForeignKey("TehsilId");
                });

            modelBuilder.Entity("NurseryAngularApplication.Model.States.District", b =>
                {
                    b.HasOne("NurseryAngularApplication.Model.States.State", "State")
                        .WithMany()
                        .HasForeignKey("StateId");
                });

            modelBuilder.Entity("NurseryAngularApplication.Model.States.Tehsil", b =>
                {
                    b.HasOne("NurseryAngularApplication.Model.States.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId");
                });
#pragma warning restore 612, 618
        }
    }
}
